### PR TITLE
[Changed] ReadMe docs now point to DevPortal

### PR DESCRIPTION
**Pull request by dom-techwriter**
:question: What
---

Replaced all the readme files with a small paragraphing pointing to a central article in our DevPortal. 

:speech_balloon: Why
---
This is so that we have a single source of truth when it comes to using our QuickStart project (so, for example, people don't think that they have to do the Python thing separate etc).

### CODE REVIEW

**Comment by menecio** [comment]
@dom-techwriter the link is not accesible, it requires login. Is this normal?

**Comment by dom-techwriter** [comment]
> @dom-techwriter the link is not accesible, it requires login. Is this normal?

Hey! It wasn't published yet - but now it is! Should work with now

**Comment by menecio** [comment]
@dom-techwriter still the same, maybe the link changes after publishing it?

**Comment by dom-techwriter** [comment]
@menecio ok, now it should work!

**Review by menecio — APPROVED** [review]

**Pull request merged**
